#
#   java-app.make
#
#   Makefile rules to build GNUstep-based Java applications.
#
#   Copyright (C) 1999 Free Software Foundation, Inc.
#
#   Author:  Lyndon Tremblay <ltremblay@mezzanine.xnot.com>
#   Author:  Ovidiu Predescu <ovidiu@net-community.com>   (from application.make)
#   Based on the original version by Scott Christley.
#
#   This file is part of the GNUstep Makefile Package.
#
#   This library is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#   
#   You should have received a copy of the GNU General Public
#   License along with this library; see the file COPYING.LIB.
#   If not, write to the Free Software Foundation,
#   59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# prevent multiple inclusions
ifeq ($(JAVA_APP_MAKE_LOADED),)
JAVA_APP_MAKE_LOADED=yes

#
# Include in the common makefile rules
#
include $(GNUSTEP_MAKEFILES)/rules.make

#
# The name of the application is in the APP_NAME variable.
# The list of application resource file are in xxx_RESOURCE_FILES
# The list of application resource directories are in xxx_RESOURCE_DIRS
# The name of the application icon (if any) is in xxx_APPLICATION_ICON
# where xxx is the application name
#

JAVA_APP_NAME:=$(strip $(JAVA_APP_NAME))

# Determine the application directory extension
ifeq ($(debug), yes)
    JAVA_APP_EXTENSION=debug
else
    JAVA_APP_EXTENSION=app
endif

ifeq ($(INTERNAL_java_app_NAME),)
# This part gets included by the first invoked make process.
internal-all:: $(JAVA_APP_NAME:=.all.java_app.variables)

internal-install:: $(JAVA_APP_NAME:=.install.java_app.variables)

internal-uninstall:: $(JAVA_APP_NAME:=.uninstall.java_app.variables)

internal-clean:: $(JAVA_APP_NAME:=.clean.java_app.variables)

internal-distclean:: $(JAVA_APP_NAME:=.distclean.java_app.variables)

$(JAVA_APP_NAME):
	@$(MAKE) -f $(MAKEFILE_NAME) --no-print-directory $@.all.java_app.variables

else

# Libraries that go before the GUI libraries
ALL_GUI_LIBS = $(ADDITIONAL_GUI_LIBS) $(AUXILIARY_GUI_LIBS) $(GUI_LIBS) \
   $(BACKEND_LIBS) $(ADDITIONAL_TOOL_LIBS) $(AUXILIARY_TOOL_LIBS) \
   $(FND_LIBS) $(ADDITIONAL_OBJC_LIBS) $(AUXILIARY_OBJC_LIBS) $(OBJC_LIBS) \
   $(SYSTEM_LIBS) $(TARGET_SYSTEM_LIBS)

ALL_GUI_LIBS := \
    $(shell $(WHICH_LIB_SCRIPT) $(LIB_DIRS_NO_SYSTEM) $(ALL_GUI_LIBS) \
	debug=$(debug) profile=$(profile) shared=$(shared) libext=$(LIBEXT) \
	shared_libext=$(SHARED_LIBEXT))


# Don't include these definitions the first time make is invoked. This part is
# included when make is invoked the second time from the %.build rule (see
# rules.make).
JAVA_APP_DIR_NAME = $(INTERNAL_java_app_NAME:=.$(JAVA_APP_EXTENSION))

# Support building NeXT applications
ifneq ($(OBJC_COMPILER), NeXT)
JAVA_APP_FILE = \
    $(JAVA_APP_DIR_NAME)/$(GNUSTEP_TARGET_DIR)/$(LIBRARY_COMBO)/$(INTERNAL_java_app_NAME)$(EXEEXT)
else
JAVA_APP_FILE = $(JAVA_APP_DIR_NAME)/$(INTERNAL_java_app_NAME)$(EXEEXT)
endif

#
# Internal targets
#

$(JAVA_APP_FILE): $(C_OBJ_FILES) $(OBJC_OBJ_FILES) $(SUBPROJECT_OBJ_FILES)
	$(LD) $(ALL_LDFLAGS) -o $(LDOUT)$@ $(C_OBJ_FILES) $(OBJC_OBJ_FILES) \
		$(SUBPROJECT_OBJ_FILES) \
		$(ALL_LIB_DIRS) $(ALL_GUI_LIBS)
ifeq ($(OBJC_COMPILER), NeXT)
	@$(TRANSFORM_PATHS_SCRIPT) `echo $(ALL_LIB_DIRS) | sed 's/-L//g'` \
		>$(JAVA_APP_DIR_NAME)/library_paths.openapp
# This is a hack for OPENSTEP systems to remove the iconheader file
# automatically generated by the makefile package.
	rm -f $(INTERNAL_java_app_NAME).iconheader
else
	@$(TRANSFORM_PATHS_SCRIPT) `echo $(ALL_LIB_DIRS) | sed 's/-L//g'` \
	>$(JAVA_APP_DIR_NAME)/$(GNUSTEP_TARGET_CPU)/$(GNUSTEP_TARGET_OS)/$(LIBRARY_COMBO)/library_paths.openapp
endif

#
# Compilation targets
#
ifeq ($(OBJC_COMPILER), NeXT)
internal-java_app-all:: before-$(TARGET)-all $(INTERNAL_java_app_NAME).iconheader \
	$(GNUSTEP_OBJ_DIR) $(JAVA_APP_DIR_NAME) $(JAVA_APP_FILE) java_app-resource-files \
	after-$(TARGET)-all

before-$(TARGET)-all::

after-$(TARGET)-all::

$(JAVA_APP_DIR_NAME):
	mkdir $@

else

internal-java_app-all:: before-$(TARGET)-all $(GNUSTEP_OBJ_DIR) \
   $(JAVA_APP_DIR_NAME)/$(GNUSTEP_TARGET_DIR)/$(LIBRARY_COMBO) $(JAVA_APP_FILE) \
   $(JAVA_APP_DIR_NAME)/$(INTERNAL_java_app_NAME) java_app-resource-files after-$(TARGET)-all

before-$(TARGET)-all::

after-$(TARGET)-all::

$(JAVA_APP_DIR_NAME)/$(GNUSTEP_TARGET_DIR)/$(LIBRARY_COMBO):
	@$(MKDIRS) $(JAVA_APP_DIR_NAME)/$(GNUSTEP_TARGET_DIR)/$(LIBRARY_COMBO)

$(JAVA_APP_DIR_NAME)/$(INTERNAL_java_app_NAME):
	cp $(GNUSTEP_MAKEFILES)/java-executable.template $(JAVA_APP_DIR_NAME)/$(INTERNAL_java_app_NAME)
	chmod a+x $(JAVA_APP_DIR_NAME)/$(INTERNAL_java_app_NAME)
endif

_FORCE::

internal-java_app-install:: internal-java_app-all internal-install-dirs
	rm -rf $(GNUSTEP_APPS)/$(JAVA_APP_DIR_NAME)
	$(TAR) cf - $(JAVA_APP_DIR_NAME) | (cd $(GNUSTEP_APPS); $(TAR) xf -)

internal-install-dirs::
	$(MKDIRS) $(GNUSTEP_APPS)

internal-java_app-uninstall::
	(cd $(GNUSTEP_APPS); rm -rf $(JAVA_APP_DIR_NAME))

#
# Cleaning targets
#
internal-java_app-clean::
	rm -rf $(GNUSTEP_OBJ_PREFIX)/$(GNUSTEP_TARGET_CPU)/$(GNUSTEP_TARGET_OS)/$(LIBRARY_COMBO)
ifeq ($(OBJC_COMPILER), NeXT)
	rm -f *.iconheader
	for f in *.$(JAVA_APP_EXTENSION); do \
	  rm -f $$f/`basename $$f .$(JAVA_APP_EXTENSION)`; \
	done
else
	rm -rf *.$(JAVA_APP_EXTENSION)/$(GNUSTEP_TARGET_CPU)/$(GNUSTEP_TARGET_OS)/$(LIBRARY_COMBO)
endif


internal-java_app-distclean::
	rm -rf shared_obj static_obj shared_debug_obj shared_profile_obj \
	  static_debug_obj static_profile_obj shared_profile_debug_obj \
	  static_profile_debug_obj *.app *.debug *.profile *.iconheader

endif

endif
# java-wrapper.make loaded

## Local variables:
## mode: makefile
## End:
